// DIZENDO O QUE SE PODE FAZER EM UM OBJETO:

// NESTE CASO POSSO APENAS DELETAR CHAVES E MODIFICAR OS VALORES DAS CAHVES.
const produto = Object.preventExtensions({
    nome: 'Maçã', preco: 1.50
})
// EXEMPLO
// NESTE CASO EU CONSIGO FAZER ESSAS MODIFICAÇÕES.
produto.preco = 1.55
delete produto.nome
// NO PRÓXIMO EXEMPLO NÃO POSSO.
produto.tag = "fruta" 
// OBJETO DEPOIS DAS MODIFICAÇÕES.
console.log(produto)

// OBJECT.SEAL({})
/* 
    DIFERENTE DO PREVENTEXTENSIONS() ESTE SELA O OBJETO ONDE VOCÊ NÃO PODE EXCLUIR E NEM ADICIONAR
    NOVAS CHAVES, APENAS LER E MODIFICAR OS VALORES DAS CHAVES. 
*/

// OBJECT.FREEZE({}) SELA E DEIXA OS OBJETOS CONSTANTES, SEJA SEU TIPO DE DADO E O DADO EM SI.