const pessoa = { nome: 'Luiz'}
Object.freeze(pessoa) // TORNANDO O OBJETO IMUTAVEL DE TODAS AS FORMAS.
/* 
    A VARIÁVEL APONTA PARA UM ENDEREÇO NA MEMÓRIA
    E ESSE ENDEREÇO SE TORNA 'INSUBSCRITIVEL', OU SEJA, IMUTAVEL.
*/